### ISSUE TITLE
CSS not properly attached to the index.html page

### ISSUE THREAD

**Issue by ritikjaiswal019** [bitsnbytes-web/tasksapp#5]
When opening the page, its not styled properly

**Comment by bitsnbytesdevelopers** [comment]
CSS not properly attached to the index.html page https://github.com/bitsnbytes-web/tasksapp/pull/6 working

**Comment by bitsnbytesdevelopers** [comment]
CSS not properly attached to the index.html page #6 working

**Comment by bitsnbytesdevelopers** [comment]
#6

**Comment by bitsnbytesdevelopers** [comment]
This Fixes #5
